
readEcgData = scan(txtFilePath)
time = seq(from = 0, to = 10, length.out(readEcgData))
time = seq(from = 0, to = 10, length.out = length(readEcgData))
plot(time, readEcgData, xlab = "t", ylab = "ecg")
plot(time, readEcgData, type = "1", xlab = "t", ylab = "ecg")
plot(time, readEcgData, type = "l", xlab = "t", ylab = "ecg")
plot(readEcgData, type = "l", xlab = "t", ylab = "ecg")
plot(time, readEcgData, type = "l", xlab = "t", ylab = "ecg")
txtFilePath = "C:/R-programing-EcgOut/ecg60HzData.txt"
time = seq(from = 0, to = 10, length.out = length(readEcgData))
plot(time, readEcgData, type = "l", xlab = "t", ylab = "ecg")
plot(time, readEcgData, type = "p", xlab = "t", ylab = "ecg")
plot(time, readEcgData, type = "b", xlab = "t", ylab = "ecg")
plot(time, readEcgData, type = "l", xlab = "t", ylab = "ecg")
txtFilePath = "C:/R-programing-EcgOut/ecg60HzData.txt"
readEcgData = scan(txtFilePath)
timeAxis = seq(from = 0, to = 10, length.out = length(readEcgData))
plot(timeAxis, readEcgData, type = "l", xlab = "t", ylab = "ecg")
rm(list=ls())
txtFilePath = "C:/R-programing-EcgOut/ecg60HzData.txt"
readEcgData = scan(txtFilePath)
timeAxis = seq(from = 0, to = 10, length.out = length(readEcgData))
plot(timeAxis, readEcgData, type = "l", xlab = "t", ylab = "ecg")
plot(timeAxis, readEcgData, type = "l", xlab = "t", ylab = "ecg")
plot(timeAxis, readEcgData, type = "l", xlab = "t", ylab = "ecg")
install.packages("zoo")
library(zoo)
moving_average <- function(x, n = 10) {
  filter(x, rep(1/n, n), sides = 2)
}
filtered_ecg <- moving_average(ecg_data, n = 5)
filtered_ecg <- moving_average(readEcgData, n = 5)
par(mfrow = c(2, 1))
plot(readEcgData, type = "l", xlab = "Index", ylab = "ECG", main = "Raw ECG Data")
plot(filtered_ecg, type = "l", xlab = "Index", ylab = "Filtered ECG", main = "Filtered ECG Data (Moving Average)")
par(mfrow = c(1, 1))
filtered_ecg <- moving_average(ecg_data, n = 8)
filtered_ecg <- moving_average(readEcgData, n = 8)
par(mfrow = c(2, 1))
plot(readEcgData, type = "l", xlab = "Index", ylab = "ECG", main = "Raw ECG Data")
plot(filtered_ecg, type = "l", xlab = "Index", ylab = "Filtered ECG", main = "Filtered ECG Data (Moving Average)")
par(mfrow = c(1, 1))
plot(readEcgData, type = "l", xlab = " ", ylab = "Raw ECG", main = "Raw ECG Data")
par(mfrow = c(2, 1))
plot(readEcgData, type = "l", xlab = " ", ylab = "Raw ECG", main = "Raw ECG Data")
plot(filtered_ecg, type = "l", xlab = " ", ylab = "Filtered ECG", main = "Filtered ECG Data (Moving Average)")
par(mfrow = c(1, 1))
time = seq(from = 0, to = 10, length.out = length(readEcgData))
par(mfrow = c(2, 1))
plot(time, readEcgData, type = "l", xlab = " ", ylab = "Raw ECG", main = "Raw ECG Data")
plot(time, filtered_ecg, type = "l", xlab = " ", ylab = "Filtered ECG", main = "Filtered ECG Data (Moving Average)")

